from setuptools import setup

setup(
    name='SpeedColor',
    version='1.0.0',
    packages=['venv.lib.python3.5.distutils', 'venv.lib.python3.5.encodings', 'venv.lib.python3.5.importlib',
              'venv.lib.python3.5.collections', 'venv.lib.python3.5.site-packages.pip',
              'venv.lib.python3.5.site-packages.pip.req', 'venv.lib.python3.5.site-packages.pip.vcs',
              'venv.lib.python3.5.site-packages.pip.utils', 'venv.lib.python3.5.site-packages.pip.compat',
              'venv.lib.python3.5.site-packages.pip.models', 'venv.lib.python3.5.site-packages.pip._vendor',
              'venv.lib.python3.5.site-packages.pip._vendor.idna',
              'venv.lib.python3.5.site-packages.pip._vendor.certifi',
              'venv.lib.python3.5.site-packages.pip._vendor.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations',
              'venv.lib.python3.5.site-packages.wheel', 'venv.lib.python3.5.site-packages.wheel.tool',
              'venv.lib.python3.5.site-packages.wheel.signatures', 'venv.lib.python3.5.site-packages.pygame',
              'venv.lib.python3.5.site-packages.pygame.docs', 'venv.lib.python3.5.site-packages.pygame.gp2x',
              'venv.lib.python3.5.site-packages.pygame.tests',
              'venv.lib.python3.5.site-packages.pygame.tests.test_utils',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.all_ok',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.exclude',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.timeout',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.failures1',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.everything',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.incomplete',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.print_stderr',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.print_stdout',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.infinite_loop',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.incomplete_todo',
              'venv.lib.python3.5.site-packages.pygame.threads', 'venv.lib.python3.5.site-packages.pygame.examples',
              'venv.lib.python3.5.site-packages.setuptools', 'venv.lib.python3.5.site-packages.setuptools.extern',
              'venv.lib.python3.5.site-packages.setuptools._vendor',
              'venv.lib.python3.5.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.5.site-packages.setuptools.command', 'venv.lib.python3.5.site-packages.pkg_resources',
              'venv.lib.python3.5.site-packages.pkg_resources.extern',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging'],
    url='https://github.com/christophercalm/SpeedColor',
    license='GPL 3.0',
    author='Christopher Calmes',
    author_email='Christopher.calmes@okbu.edu',
    description='Game that tests the ability of a person to differentiate colors'
)
